@extends('layouts.app')

@section('title')
    Add New Project
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title text-center">Add New Project</h1>
                @include('flash::message')
                @include('partials.js-alert')
                <p><sup class="text-danger">*</sup> All fields marked with a red asterisk are required.</p>
                <p><em><strong>NB:</strong> The fields marked in gray are going to be automatically generated by the system.</em></p>
                <hr>
            </div>
        </div>

        {!! Form::open(['route' => 'projects.create', 'class' => 'form js-form', 'data-reset' => 1]) !!}
            @include('projects.form')

            <div class="row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-warning" data-text-default="Submit New Project" data-text-progress="Submitting...">Submit New Project</button>
                </div>
            </div>
        </form>
        @include('modals.beneficiary')
        @include('modals.os-conf')

        <hr>

        <h4 class="form-heading">Donors and Contributions</h4>
        <p class="text-warning">No Donors added yet. Following submission of the new project you will be able to add Donors.</p>

        <hr>

        <h4 class="form-heading">Project Documents</h4>
        <p class="text-warning">No Documents added yet. Following submission of the new project you will be able to add Documents.</p>

    </div>
@stop

@section('scripts')
<script src="{{ Helper::asset('assets/js/project.js') }}"></script>
@stop
