@extends('layouts.app')

@section('title')
    Create New Twinning Relationship
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title text-center">Create New Twinning Relationship</h1>
                @include('flash::message')
                @include('partials.js-alert')
                <p><sup class="text-danger">*</sup> All fields marked with a red asterisk are required.</p>
                <p><em><strong>NB:</strong> The fields marked in gray are going to be automatically generated by the system.</em></p>
                <hr>
            </div>
        </div>

        {!! Form::open(['route' => 'twinnings.create', 'class' => 'form js-form', 'data-reset' => 1]) !!}
            @include('twinnings.form')

            <div class="row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-warning" data-text-default="Submit New Twinning" data-text-progress="Submitting...">Submit New Twinning</button>
                </div>
            </div>
        </form>

        <hr>

        @include('modals.local-conf')
        @include('modals.os-conf')

        <h4 class="form-heading">Twinning Documents</h4>
        <p class="text-warning">No Documents added yet. Following submission of the new conference you will be able to add Documents.</p>

    </div>
@stop

@section('scripts')
<script src="{{ Helper::asset('assets/js/twinning.js') }}"></script>
@stop
