@extends('layouts.app')

@section('title')
    Edit Existing Twinning
@stop

@php
    use App\User;
@endphp

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title text-center">Existing Twinning</h1>
            </div>
            <div class="col-sm-5 note-below-title">
                <p><sup class="text-danger">*</sup> All fields marked with a red asterisk are required.</p>
                <p><em><strong>NB:</strong> The fields marked in gray are going to be <br>&emsp;&emsp;automatically generated by the system.</em></p>
            </div>
        </div>
            @include('flash::message')
            @include('partials.js-alert')

            <hr>

        {!! Form::model($twinning, ['route' => ['twinnings.edit', $twinning], 'class' => 'form js-form', 'method' => 'patch']) !!}
            <div class="col-sm-6 mb-2 pull-right" style="text-align:right">
                Last Updated on: <strong data-bind="updated_date">{{ $twinning->updated_at->format('d/m/Y') }}</strong> at <strong data-bind="updated_time">{{ $twinning->updated_at->format('H:i') }}</strong> by <strong data-bind="updated_name">@if ($twinning->updated_by) {{ $twinning->updated_by->getFullName() }} @else {{ "Anonymous" }} @endif</strong><br />
                Created on: <strong data-bind="created_date"> {{ $twinning->created_at->format('d/m/Y') }} </strong> at <strong data-bind="updated_time">{{ $twinning->updated_at->format('H:i') }}</strong><br />
                <a data-toggle="modal" id="getActivity" class="btn btn-primary btn-sm mb-2 mt-1"  data-target="#messageBoard" data-url="{{ url('twinning',['id'=>$twinning->id])}}" href="#."> Log </a>
            </div>

            @include('twinnings.form')

            @if ($currentUser->hasPermissionTo('update.twinnings'))
                <div class="row">
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-warning" data-text-default="Apply changes to Twinning" data-text-progress="Applying...">Apply changes to Twinning</button>
                    </div>
                </div>
            @endif
        </form>

        <hr>
        <p>

        {!! Form::model($twinning, ['route' => ['twinnings.addComment', $twinning->id], 'class' => 'form js-form-comment', 'method' => 'patch']) !!}
            @include('twinnings.comment')
        </form>

        <hr>
        @if($currentUser->hasRole('Full Admin'))
            @include('modals.local-conf')
            @include('modals.os-conf')
        @endif

        <h4 class="form-heading">Twinning Documents</h4>

        <div class="section-documents" data-id="{{ $twinning->id }}" data-type="Twinning"><i class="fa fa-spinner fa-pulse fa-fw"></i> Loading...</div>
        @if(!$currentUser->hasRole('State User Finance','State User'))
        @include('modals.document.create')
        @include('modals.document.edit')
        @endif
        @include('mustache.documents')


        <p>
        <p>
    </div>

    <div class="modal fade bd-example-modal-lg" id="messageBoard" tabindex="-1"  role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Activity Log</h4>
                </div>

                <div class="modal-body" style="overflow-x: scroll">
                    <div class="pull-right mb-1">
                        <a href="{{ route('twinnings.exportIndividualLog', $twinning->id) }}" class="btn btn-default">Export Twinning Log</a>
                    </div>
                    <table class="table table-striped js-modal-table" data-page-length="{{ config('vinnies.pagination.activity') }}" data-order-col="1" data-order-type="ASC">
                        <thead>
                            <tr>
                                <th class="text-center" data-name="id">Log ID</th>
                                <th class="text-center" data-name="event">Event Type</th>
                                <th class="text-center" data-name="subjectID">Subject ID</th>
                                <th width="100" class="text-center" data-name="properties">Properties Changes</th>
                                <th class="text-center" data-name="updated_at">Updated At</th>
                                <th class="text-center" data-name="updated_by">Updated By</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($activity as $activities)
                            <tr>
                                <td>{{ $activities->id }}</td>
                                <td>
                                    <?php
                                        $event = explode('\\',$activities->subject_type);
                                        if($event[1] != 'Twinning'){
                                            echo $event[1];
                                        }
                                    ?>
                                    {{ $activities->event }}</td>
                                <td>{{ $activities->subject_id }}</td>
                                <td>
                                    <div style="display: flex; column-gap: 3rem">
                                        <div>
                                            
                                            @if(isset($activities->properties['old']) )
                                            <h5>Old</h5>
                                                @foreach ($activities->properties['old'] as $field => $value)
                                                    @if(!is_array($activities->properties['old'][$field]))
                                                    <p><strong> {{ $field }} : </strong> {{$activities->properties['old'][$field] }} </p>
                                                    @else
                                                    <p><strong> {{ $field }} : </strong> </p>
                                                    <ul>
                                                    @foreach($activities->properties['old'][$field] as $key => $secondValue)
                                                        <li>{{ $activities->properties['old'][$field][$key] }}</li>
                                                    @endforeach
                                                    </ul>
                                                    @endif
                                                @endforeach
                                            @endif
                                        </div>
                                        <div>
                                            
                                            @if(isset($activities->properties['attributes']) )
                                            <h5>Changes</h5>
                                                @foreach ($activities->properties['attributes'] as $field => $value)
                                                    @if(!is_array($activities->properties['attributes'][$field]))
                                                    <p><strong> {{ $field }} : </strong> {{$activities->properties['attributes'][$field] }} </p>
                                                    @else
                                                    <p><strong> {{ $field }} : </strong> </p>
                                                    <ul>
                                                    @foreach($activities->properties['attributes'][$field] as $key => $secondValue)
                                                        <li>{{ $activities->properties['attributes'][$field][$key] }}</li>
                                                    @endforeach
                                                    </ul>
                                                    @endif
                                                @endforeach
                                            @endif
                                        </div>
                                    </div>
                                  

                                </td>                          
                                <td>{{ date('d-m-Y H:i:s', strtotime($activities->updated_at)) }}</td>
                                @php
                                    $user = User::where('id', $activities->causer_id)->withTrashed()->first();
                                @endphp
                                @if ($user)
                                    <td>{{ $user->first_name . ' ' . $user->last_name }}</td>
                                @else
                                    <td>{{ $activities->causer_id }}</td>
                                @endif
                            </tr> 
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('scripts')
<script src="{{ Helper::asset('assets/js/twinning.js') }}"></script>
@stop
