@extends('layouts.app')

@section('title')
    Add Beneficiary
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title text-center">Add Beneficiary</h1>
                @include('flash::message')
                @include('partials.js-alert')
                <p><sup class="text-danger">*</sup> All fields marked with a red asterisk are required.</p>
                <p><em><strong>NB:</strong> The fields marked in gray are going to be automatically generated by the system.</em></p>
                <hr>
            </div>
        </div>

        {!! Form::open(['route' => 'beneficiaries.create', 'class' => 'form js-form', 'data-reset' => 1]) !!}
            @include('beneficiaries.form')

            <div class="row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-warning" data-text-default="Submit New Beneficiary" data-text-progress="Submitting...">Submit New Beneficiary</button>
                </div>
            </div>

            <hr>

            <h4 class="form-heading">Beneficiary Documents</h4>
            <p class="text-warning">No Documents added yet. Following submission of the new beneficiary you will be able to add Documents.</p>

        </form>
    </div>
@stop

@section('scripts')
<script src="{{ Helper::asset('assets/js/beneficiary.js') }}"></script>
@stop
