@extends('layouts.app')

@section('title')
    Two-Factor Authentication
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12 intro">
                <h1 class="page-title text-center">Two-Factor Authentication</h1>

                @if (session('status'))
                    <div class="alert alert-success">{{ session('status') }}</div>
                @endif

                @if(session('msg'))
	                <div class="alert alert-danger">
		                {{ session('msg') }}
	                </div>
                @endif

                @if ($currentUser->hasGoogle2FAEnabled())
                    <p>Congratulations! Your account is currently protected with two-factor authentication. To disable two-factor authentication, please click the button below.</p>

                    <form action="{{ route('2fa.disable') }}" method="post" >
                        @csrf
                        @method('PATCH')

                        <button type="submit" class="btn btn-danger">Disable two-factor authentication</button>
                    </form>
                @else
                    <p>To enable two-factor authentication for your account, scan this QR code with <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank">Google Authenticator app</a> or any other compatible two-factor authentication app like <a href="https://authy.com" target="_blank">Authy</a>.</p>
                    <img src="{{ $qr_code_url }}" alt="{{ __('QR Code') }}" style="max-width:200px;display:block;margin-bottom:30px;">
                    <p>{{ __('Once you\'ve scanned the QR code, enter the 6-digits verification code generated by the app into the field below. ') }}</p>
                    <form action="{{ route('2fa.enable') }}" method="post" >
                        @csrf
                        @method('PATCH')

                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label for="one_time_password">Authentication Code</label>
                                    <input type="text" name="one_time_password" id="one_time_password" class="form-control" required autocomplete="new-password">
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Enable two-factor authentication</button>
                    </form>
                @endif
            </div>
        </div>
    </div>
@stop
