@extends('layouts.app')

@section('title')
    Add New Overseas Conference
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="page-title text-center">Add New Overseas Conference</h1>
                @include('flash::message')
                @include('partials.js-alert')
                <p><sup class="text-danger">*</sup> All fields marked with a red asterisk are required.</p>
                <p><em><strong>NB:</strong> The fields marked in gray are going to be automatically generated by the system.</em></p>
                <hr>
            </div>
        </div>

        {!! Form::open(['route' => 'overseas-conferences.create', 'class' => 'form js-form', 'data-reset' => 1]) !!}
            @include('overseas-conferences.form')

            <div class="row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-warning" data-text-default="Submit New Overseas Conference" data-text-progress="Submitting...">Submit New Overseas Conference</button>
                </div>
            </div>
        </form>

        <hr>

        <h4 class="form-heading">Twins</h4>
        <p class="text-warning">No Twins added yet. Following submission of the new conference you will be able to add Twins.</p>

        <hr>

        <h4 class="form-heading">Linked Projects</h4>
        <p class="text-warning">No Projects.</p>

        <hr>

        <h4 class="form-heading">Overseas Conference Documents</h4>
        <p class="text-warning">No Documents added yet. Following submission of the new conference you will be able to add Documents.</p>

    </div>
@stop

@section('scripts')
<script src="{{ Helper::asset('assets/js/overseas-conference.js') }}"></script>
@stop
